# Generated by Django 4.0.3 on 2022-04-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='avatar',
            field=models.FileField(blank=True, max_length=128, null=True, upload_to='avatar/', verbose_name='头像'),
        ),
    ]
