# Generated by Django 4.0.3 on 2022-04-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_admin_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.CharField(max_length=12, verbose_name='车牌号')),
                ('order_id', models.CharField(max_length=64, verbose_name='订单编号')),
                ('start_time', models.DateTimeField(verbose_name='驶入时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='驶出时间')),
                ('park_id', models.CharField(max_length=8, verbose_name='车位编号')),
                ('is_read', models.SmallIntegerField(choices=[(1, '已读'), (2, '未读')], default=2, verbose_name='消息状态')),
                ('price', models.FloatField(verbose_name='累计金额')),
            ],
        ),
    ]
