# Generated by Django 4.0.3 on 2022-04-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '已完成'), (2, '未完成')], default=2, verbose_name='状态'),
        ),
    ]
