# Generated by Django 4.0.3 on 2022-04-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_message_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='card',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='车牌号'),
        ),
        migrations.AlterField(
            model_name='message',
            name='order_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='订单编号'),
        ),
        migrations.AlterField(
            model_name='message',
            name='park_id',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='车位编号'),
        ),
        migrations.AlterField(
            model_name='message',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='累计金额'),
        ),
        migrations.AlterField(
            model_name='message',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='驶入时间'),
        ),
    ]
