# Generated by Django 4.0.3 on 2022-04-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_message_park_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='card',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='车牌号'),
        ),
        migrations.AddField(
            model_name='admin',
            name='type',
            field=models.SmallIntegerField(choices=[(1, '管理员'), (2, '用户')], default=2, verbose_name='账户类型'),
        ),
    ]
