# Generated by Django 4.0.3 on 2022-04-30 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_admin_card_admin_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='user_is_read',
            field=models.SmallIntegerField(choices=[(1, '已读'), (2, '未读')], default=2, verbose_name='用户消息状态'),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_read',
            field=models.SmallIntegerField(choices=[(1, '已读'), (2, '未读')], default=2, verbose_name='管理员消息状态'),
        ),
    ]
